version: '3.7'

services:
  postgres:
    container_name: "postgres_merlot"
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - "gaia-x"

  neo4j:
    container_name: "neo4j_merlot"
    image: neo4j:4.4.12
    environment:
      NEO4J_AUTH: "${GRAPH_STORE_USER}/${GRAPH_STORE_PASSWORD}"
      NEO4J_dbms_connector_http_listen__address: :7474
      NEO4J_dbms_connector_bolt_listen__address: :7687
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science", "n10s"]'
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*,n10s.*
      NEO4J_dbms_security_procedures_allowlist: gds.*,apoc.*,n10s.*
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - "gaia-x"
    restart: on-failure
    command: neo4j

  server:
    container_name: "fc-server_merlot"
    build:
      context: ~/gxfs/fc-service/fc-service-server
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: "${FC_CLIENT_SECRET}"
      KEYCLOAK_AUTH-SERVER-URL: "${KEYCLOAK_AUTH_SERVER_URL}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "${ISSUER_URI}"
      SPRING_DATASOURCE_URL: "${DB_URL}"
      GRAPHSTORE_URI: "${GRAPH_STORE_URI}"
      GRAPHSTORE_USER: "${GRAPH_STORE_USER}"
      GRAPHSTORE_PASSWORD: "${GRAPH_STORE_PASSWORD}"
    ports:
      - "8081:8081"
    networks:
      - "gaia-x"
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:127.0.0.1"
    restart: on-failure
    depends_on:
      - postgres
      - neo4j

  keycloak:
    container_name: "keycloak_merlot"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    image: "quay.io/keycloak/keycloak:20.0.5"
    ports:
      - "8080:8080"
    restart: on-failure
    command:
      [
          'start-dev --auto-build'
      ]
  
  rabbitmq:
    container_name: "rabbitmq_merlot"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "9090:15672"
      - "5672:5672"
    restart: on-failure
    hostname: rabbitmq-merlot
  
  aaamorchestrator:
    container_name: "aaam-orchestrator"
    build:
      context: ~/merlotMPO/aaam-orchestrator
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_BASEURI: "http://key-server:8080"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "http://key-server:8080/realms/POC1"
    ports:
      - "8083:8083"
    restart: on-failure
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:host-gateway"

  organizationsorchestrator:
    container_name: "organizations-orchestrator"
    build:
      context: ~/merlotMPO/organisations-orchestrator
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_BASEURI: "http://key-server:8080"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "http://key-server:8080/realms/POC1"
      KEYCLOAK_CLIENTSECRET: "${FC_CLIENT_SECRET}"
    ports:
      - "8082:8082"
    restart: on-failure
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:host-gateway"

  sdcreationwizardapi:
    container_name: "sd-creation-wizard-api_merlot"
    build:
      context: ~/merlotMPO/sd-creation-wizard-api
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: "8085"
    ports:
      - "8085:8085"
    restart: on-failure


networks:
  gaia-x:
    driver: "bridge"
