version: '3.7'

services:
  vault:
    user: "${UID}:${GID}"
    container_name: "vault"
    hostname: vault
    image: vault:1.9.7
    restart: on-failure
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
    expose:
      - "8200"
    ports:
      - "8200:8200"
    networks:
      - "gaia-x"
    volumes:
      - ./docker_data/vault/file:/vault/file
      - ./docker_data/vault/logs:/vault/logs
      
  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - "gaia-x"

  postgres:
    user: "${UID}:${GID}"
    container_name: "postgres_merlot"
    hostname: postgres
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - "gaia-x"
    volumes:
      - ./docker_data/postgres/data:/var/lib/postgresql/data

  neo4j:
    user: "${UID}:${GID}"
    container_name: "neo4j_merlot"
    hostname: neo4j
    image: neo4j:5.7.0
    environment:
      NEO4J_AUTH: "${GRAPH_STORE_USER}/${GRAPH_STORE_PASSWORD}"
      NEO4J_dbms_connector_http_listen__address: :7474
      NEO4J_dbms_connector_bolt_listen__address: :7687
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science", "n10s"]'
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*,n10s.*,semantics.*
      NEO4J_dbms_security_procedures_allowlist: gds.*,apoc.*,n10s.*,semantics.*
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - "gaia-x"
    restart: on-failure
    command: neo4j
    volumes:
      - ./docker_data/neo4j/data:/data
      - ./docker_data/neo4j/logs:/logs

  server:
    user: "${UID}:${GID}"
    container_name: "fc-server_merlot"
    hostname: fc-server
    image: ghcr.io/merlot-education/gxfs-catalog:latest
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: "${FC_CLIENT_SECRET}"
      KEYCLOAK_AUTH-SERVER-URL: "${KEYCLOAK_AUTH_SERVER_URL}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "${ISSUER_URI}"
      SPRING_DATASOURCE_URL: "${DB_URL}"
      GRAPHSTORE_URI: "${GRAPH_STORE_URI}"
      GRAPHSTORE_USER: "${GRAPH_STORE_USER}"
      GRAPHSTORE_PASSWORD: "${GRAPH_STORE_PASSWORD}"
      FEDERATEDCATALOGUE_VERIFICATION_PARTICIPANT_TYPE: http://w3id.org/gaia-x/core#Participant
      FEDERATEDCATALOGUE_VERIFICATION_SERVICEOFFERING_TYPE: http://w3id.org/gaia-x/core#ServiceOffering
    ports:
      - "8081:8081"
    networks:
      - "gaia-x"
    extra_hosts:
      - "localhost:127.0.0.1"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  keycloak:
    user: "${UID}:${GID}"
    container_name: "keycloak_merlot"
    hostname: key-server
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HEALTH_ENABLED: true
    image: "quay.io/keycloak/keycloak:20.0.5"
    ports:
      - "8080:8080"
    networks:
      - "gaia-x"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "--head", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15
    command:
      [
          'start-dev --import-realm --health-enabled=true'
      ]
    volumes:
      - ./docker_data/keycloak/data:/opt/keycloak/data
      - ./docker_data/keycloak/providers:/opt/keycloak/providers

  rabbitmq:
    user: "${UID}:${GID}"
    container_name: "rabbitmq_merlot"
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "9090:15672"
      - "5672:5672"
    networks:
      - "gaia-x"
    restart: on-failure
    volumes:
      - ./docker_data/rabbitmq:/var/lib/rabbitmq

  sd-creation-wizard-api:
    user: "${UID}:${GID}"
    container_name: "sd-creation-wizard-api"
    hostname: wizard
    build:
      context: ../sd-creation-wizard-api
      dockerfile: Dockerfile
    networks:
      - "gaia-x"
    ports:
      - "8085:8080"

  contract-orchestrator:
    user: "${UID}:${GID}"
    container_name: "contract-orchestrator"
    hostname: contract-orchestrator
    build:
      context: ../contract-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      ORGANIZATIONSORCHESTRATOR_BASEURI: "http://organisations-orchestrator:8082/api"
      SERVICEOFFERING_BASEURI: "http://serviceoffering-orchestrator:8084/api"
    networks:
      - "gaia-x"
    ports:
      - "8086:8086"
    volumes:
      - ./docker_data/contract-orchestrator/data:/data
    depends_on:
      keycloak:
        condition: service_healthy

  serviceoffering-orchestrator:
    user: "${UID}:${GID}"
    container_name: "serviceoffering-orchestrator"
    hostname: serviceoffering-orchestrator
    build:
      context: ../serviceoffering-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      GXFSCATALOG_BASEURI: "http://fc-server:8081"
      GXFSWIZARD_BASEURI: "http://wizard:8080"
      ORGANIZATIONSORCHESTRATOR_BASEURI: "http://organisations-orchestrator:8082/api"
      KEYCLOAK_CLIENTSECRET: "${FC_CLIENT_SECRET}"
    networks:
      - "gaia-x"
    ports:
      - "8084:8084"
    volumes:
      - ./docker_data/serviceoffering-orchestrator/data:/data
    depends_on:
      keycloak:
        condition: service_healthy

  organisations-orchestrator:
    user: "${UID}:${GID}"
    container_name: "organisations-orchestrator"
    hostname: organisations-orchestrator
    build:
      context: ../organisations-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      GXFSCATALOG_BASEURI: "http://fc-server:8081"
      GXFSWIZARD_BASEURI: "http://wizard:8080"
      KEYCLOAK_CLIENTSECRET: "${FC_CLIENT_SECRET}"
    networks:
      - "gaia-x"
    ports:
      - "8082:8082"
    volumes:
      - ./docker_data/organisations-orchestrator/data:/data
    depends_on:
      keycloak:
        condition: service_healthy

  aaam-orchestrator:
    user: "${UID}:${GID}"
    container_name: "aaam-orchestrator"
    hostname: aaam-orchestrator
    build:
      context: ../aaam-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    networks:
      - "gaia-x"
    ports:
      - "8083:8083"
    depends_on:
      keycloak:
        condition: service_healthy

  marketplace:
    user: "${UID}:${GID}"
    container_name: "marketplace"
    build:
      context: ../marketplace
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    ports:
      - "4200:80"
    networks:
      - "gaia-x"


networks:
  gaia-x:
    driver: "bridge"

secrets:
  GIT_AUTH_TOKEN:
    file: "secrets/git_auth_token.txt"
