version: '3.7'

services:
  vault:
    user: "${UID}:${GID}"
    container_name: "vault"
    image: vault:1.9.7
    restart: on-failure
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
    expose:
      - "8200"
    ports:
      - "8200:8200"
    networks:
      - "gaia-x"
    volumes:
      - ./docker_data/vault/file:/vault/file
      - ./docker_data/vault/logs:/vault/logs
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - "gaia-x"

  postgres:
    user: "${UID}:${GID}"
    container_name: "postgres_merlot"
    hostname: postgres
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - "gaia-x"
    volumes:
      - ./docker_data/postgres/data:/var/lib/postgresql/data

  neo4j:
    user: "${UID}:${GID}"
    container_name: "neo4j_merlot"
    hostname: neo4j
    image: neo4j:4.4.28
    environment:
      NEO4J_AUTH: "${GRAPH_STORE_USER}/${GRAPH_STORE_PASSWORD}"
      NEO4J_dbms_connector_http_listen__address: :7474
      NEO4J_dbms_connector_bolt_listen__address: :7687
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*,n10s.*
      NEO4J_dbms_security_procedures_allowlist: gds.*,apoc.*,n10s.*
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - "gaia-x"
    restart: on-failure
    command: neo4j
    volumes:
      - ./docker_data/neo4j/data:/data
      - ./docker_data/neo4j/logs:/logs
      - ./docker_data/neo4j/plugins:/plugins

  server:
    user: "${UID}:${GID}"
    container_name: "fc-server_merlot"
    image: ghcr.io/merlot-education/catalog-shapes/gxfs-catalog:afad431
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: "${FC_CLIENT_SECRET}"
      KEYCLOAK_AUTH-SERVER-URL: "${KEYCLOAK_AUTH_SERVER_URL}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "${ISSUER_URI}"
      SPRING_DATASOURCE_URL: "${DB_URL}"
      GRAPHSTORE_URI: "${GRAPH_STORE_URI}"
      GRAPHSTORE_USER: "${GRAPH_STORE_USER}"
      GRAPHSTORE_PASSWORD: "${GRAPH_STORE_PASSWORD}"
      FEDERATEDCATALOGUE_VERIFICATION_PARTICIPANT_TYPE: http://w3id.org/gaia-x/core#Participant
      FEDERATEDCATALOGUE_VERIFICATION_SERVICEOFFERING_TYPE: http://w3id.org/gaia-x/core#ServiceOffering
      FEDERATEDCATALOGUE_IGNORESSL: true
    network_mode: "host"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  keycloak:
    user: "${UID}:${GID}"
    container_name: "keycloak_merlot"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HEALTH_ENABLED: true
    image: "quay.io/keycloak/keycloak:20.0.5"
    ports:
      - "8080:8080"
    networks:
      - "gaia-x"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "--head", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15
    command:
      [
          'start-dev --import-realm --health-enabled=true'
      ]
    volumes:
      - ./docker_data/keycloak/data:/opt/keycloak/data
      - ./docker_data/keycloak/providers:/opt/keycloak/providers

  rabbitmq:
    user: "${UID}:${GID}"
    container_name: "rabbitmq_merlot"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "9090:15672"
      - "5672:5672"
    networks:
      - "gaia-x"
    restart: on-failure
    volumes:
      - ./docker_data/rabbitmq:/var/lib/rabbitmq

  sd-creation-wizard-api:
    user: "${UID}:${GID}"
    container_name: "sd-creation-wizard-api"
    image: ghcr.io/merlot-education/catalog-shapes/sd-creation-wizard-api:f3867b4
    networks:
      - "gaia-x"
    ports:
      - "8085:8080"

  contract-orchestrator:
    user: "${UID}:${GID}"
    container_name: "contract-orchestrator"
    build:
      context: ../contract-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
      SPRING_RABBITMQ_HOST: "localhost"
      ORGANIZATIONSORCHESTRATOR_BASEURI: "http://localhost:8082/api"
      SERVICEOFFERINGORCHESTRATOR_BASEURI: "http://localhost:8084/api"
    volumes:
      - ./docker_data/contract-orchestrator/data:/data
    depends_on:
      keycloak:
        condition: service_healthy
    network_mode: "host"

  serviceoffering-orchestrator:
    user: "${UID}:${GID}"
    container_name: "serviceoffering-orchestrator"
    build:
      context: ../serviceoffering-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
      SPRING_RABBITMQ_HOST: "localhost"
      GXFSCATALOG_BASEURI: "http://localhost:8081"
      GXFSWIZARDAPI_BASEURI: "http://localhost:8085"
      ORGANIZATIONSORCHESTRATOR_BASEURI: "http://localhost:8082/api"
      KEYCLOAK_CLIENTSECRET: "${FC_CLIENT_SECRET}"
      GXFSCATALOG_PRIVATEKEYPATH: ""
      GXFSCATALOG_CERTPATH: ""
      GXFSCATALOG_VERIFICATIONMETHOD: "did:web:compliance.lab.gaia-x.eu"
    volumes:
      - ./docker_data/serviceoffering-orchestrator/data:/data
    depends_on:
      keycloak:
        condition: service_healthy
    network_mode: "host"

  organisations-orchestrator:
    user: "${UID}:${GID}"
    container_name: "organisations-orchestrator"
    build:
      context: ../organisations-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      INITDATA_ORGANISATIONS: /opt/initdata/organisations/
      INITDATA_CONNECTORS: /opt/initdata/initial-orga-connectors.json
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
      SPRING_RABBITMQ_HOST: "localhost"
      GXFSCATALOG_BASEURI: "http://localhost:8081"
      GXFSWIZARDAPI_BASEURI: "http://localhost:8085"
      KEYCLOAK_CLIENTSECRET: "${FC_CLIENT_SECRET}"
      GXFSCATALOG_PRIVATEKEYPATH: ""
      GXFSCATALOG_CERTPATH: ""
      GXFSCATALOG_VERIFICATIONMETHOD: "did:web:compliance.lab.gaia-x.eu"
    volumes:
      - ./docker_data/organisations-orchestrator/data:/data
    depends_on:
      keycloak:
        condition: service_healthy
      server:
        condition: service_started
    network_mode: "host"

  aaam-orchestrator:
    user: "${UID}:${GID}"
    container_name: "aaam-orchestrator"
    build:
      context: ../aaam-orchestrator
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    depends_on:
      keycloak:
        condition: service_healthy
    network_mode: "host"

  marketplace:
    user: "${UID}:${GID}"
    container_name: "marketplace"
    build:
      context: ../marketplace
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    ports:
      - "4200:80"
    networks:
      - "gaia-x"

  did-service:
    user: "${UID}:${GID}"
    container_name: "did-service"
    build:
      context: ../did-service
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/data/database.db"
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./docker_data/did-service/data:/data
    network_mode: "host"

  pdfservice:
    user: "${UID}:${GID}"
    container_name: "pdfservice"
    image: ghcr.io/merlot-education/pdfservice:0.1.1
    networks:
      - "gaia-x"
    ports:
      - "5154:8080"
  
  edc1:
    container_name: "edc1"
    build:
      context: ../merlot-edc
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      WEB_HTTP_PORT: 29191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 29193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 29194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_PUBLIC_PORT: 29291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 29192
      WEB_HTTP_CONTROL_PATH: /control
      EDC_PARTICIPANT_ID: edc1
      EDC_DSP_CALLBACK_ADDRESS: http://localhost:8123/edc1/protocol
      EDC_API_AUTH_KEY: 1234
    env_file: "secrets/edc_ionos_secrets.txt"
    network_mode: "host"

  edc2:
    container_name: "edc2"
    build:
      context: ../merlot-edc
      dockerfile: Dockerfile
      secrets:
        - "GIT_AUTH_TOKEN"
    environment:
      WEB_HTTP_PORT: 19191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 19193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 19194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_PUBLIC_PORT: 19291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 19192
      WEB_HTTP_CONTROL_PATH: /control
      EDC_PARTICIPANT_ID: edc2
      EDC_DSP_CALLBACK_ADDRESS: http://localhost:8123/edc2/protocol
      EDC_API_AUTH_KEY: 5678
    env_file: "secrets/edc_ionos_secrets.txt"
    network_mode: "host"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker_data/nginx/reverse_proxy.conf:/etc/nginx/nginx.conf
    network_mode: "host"

networks:
  gaia-x:
    driver: "bridge"

secrets:
  GIT_AUTH_TOKEN:
    file: "secrets/git_auth_token.txt"
