CREATE DATABASE contract;
GRANT ALL PRIVILEGES ON DATABASE contract TO postgres;

CREATE DATABASE didservice;
GRANT ALL PRIVILEGES ON DATABASE didservice TO postgres;

CREATE DATABASE gxfs;
GRANT ALL PRIVILEGES ON DATABASE gxfs TO postgres;

CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;

CREATE DATABASE organisations;
GRANT ALL PRIVILEGES ON DATABASE organisations TO postgres;